name: Clone a Repo
    
on:
  workflow_dispatch:
    inputs:
        git_url:
            type: string
            default: https://github.com/VamshiVar/Actions_Learn

jobs:
  Clone-Repo:
    runs-on: ubuntu-latest

    env:
     GIT_USER: ${{ secrets.GIT_USER }}
     GIT_PAT: ${{ secrets.GIT_PAT }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: clone the repo
        id: getVersion
        run: |
          git clone ${{ inputs.git_url }} app/code

      - name: List contents
        run: ls -ltr
         
