name: Clone a Repo
    
on:
  workflow_dispatch:

jobs:
  Clone-Repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: clone the repo
        id: getVersion
        run: |
          git clone https://$GIT_USER:$GIT_PAT@github.com/VamshiVar/JenkinsLearn.git app/code
        env:
         GIT_USER: ${{ secrets.GIT_USER }}
         GIT_PAT: ${{ secrets.GIT_PAT }}

      - name: List contents
        run: ls -ltr
         
