name: Greetings

on:
  workflow_dispatch :
    inputs :
      name :
       description : "To Greet"
       default : "Friends"
       required : true
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name : send greeting
      run : echo "Hello ${{github.event.inputs.name}}"
