name: Greetings

on:
  workflow_dispatch :
    inputs:
      org:
        description: "invoking org"
        required: false
        type: string
        default: "None"
      repo:
        description: "invoking repo"
        required: true
        type: string
        default: "None"
      check_run_id:
        description: "check run id to update post job completion"
        required: true
        type: string
        default: "1"

concurrency:
  group: FrontEnd
  cancel-in-progress: true
jobs:
  Env-Test:
    runs-on: ubuntu-latest
    steps:
    - name : Build
      run : echo "Hello ${{ github.workflow }}-${{ github.ref	}}"
        
      
