name: Greetings

on:
  workflow_dispatch :
    inputs :
      org:
        description: "invoking org"
        required: false
        type: string
        default: "None"
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name : send greeting
      run : echo "Hello ${{github.event.inputs.name}}"
