name: Test Plan Stage of CD
on:
  workflow_dispatch:

jobs:
  Planning-Stage:
    runs-on: ubuntu-latest
    env:
      versionCoreData: '10,12'

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: getRequiredTfVersion
        run: |
          if [ -n "$versionCoreData" ]; then
            IFS=',' read -ra versionCoreArray <<< "$versionCoreData"
            for version in "${versionCoreArray[@]}"; do
             echo "$version"
            done
          fi
