name: Test Plan Stage of CD
on:
  workflow_dispatch:

jobs:
  Planning-Stage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: getRequiredTfVersion
        run: |
          versionCoreData = [16, 13]
          if [-n "$versionCoreData"]; then
            versionCoreArray = ($(echo $versionCoreData | jq -r '.[]'))
            echo $versionCoreArray
