name: Test Plan Stage of CD
on:
  workflow_dispatch:

jobs:
  Planning-Stage:
    runs-on: ubuntu-latest
    env:
      versionCoreData: '10,12'

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: getRequiredTfVersion
        run: |
          if [ -n "$versionCoreData" ]; then
            IFS=',' read -ra versionCoreArray <<< "$versionCoreData"
            for version_get in "${versionCoreArray[@]}"; do
             echo "$version_get"
            done

            if [ "${#version_get[@]}" -gt 1 ]; then
              echo "Error in deriving terraform minimum required version. Got more than one required_version configuration from terraform deployment source : ${version_get[@]}. Please keep only one required_version configuration."
              exit 1
            else
              firstVersionVersionConstraint = $(echo ${version_get[0]} | cut -d',' -fi)
              version = $(echo $firstVersionVersionConstraint | sed -E 's/[=|!|>|<|~ ]+//g')
              echo "Terraform minimum required version derived from terraform deployment source's required_version : $version"
            fi
            
          fi
