name: Test Plan Stage of CD
on:
  workflow_dispatch:

jobs:
  Planning-Stage:
    runs-on: ubuntu-latest
    env:
      versionCoreData: '0.13.5'
      versionRestrictFrom: '1.6'

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: getRequiredTfVersion
        run: |
          if [ -n "$versionCoreData" ]; then
            IFS=',' read -ra versionCoreArray <<< "$versionCoreData"
            echo "${versionCoreArray[@]}"
            
            if [ "${#versionCoreArray[@]}" -gt 1 ]; then
              echo "Error in deriving terraform minimum required version. Got more than one required_version configuration from terraform deployment source : ${versionCoreArray[@]}. Please keep only one required_version configuration."
              exit 1
            else
              firstVersionVersionConstraint="${versionCoreArray[0]}"
              version=$(echo "$firstVersionVersionConstraint" | sed -E 's/[=|!|>|<|~ ]+//g')
              echo "${version}"
              echo "Terraform minimum required version derived from terraform deployment source's required_version : $version"
            fi
              if [ "$(echo -e "$version\n$versionRestrictFrom" | sort -V | head -n1)" == "$versionRestrictFrom" ]; then
               echo "The provided Terraform version is restricted for usage. If you have any concerns, please get in touch with the Chofer DevEx Team via the Chofer Chare channel"
               exit 1
              else
                echo "Installing Terraform version $version"
              fi
          fi

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '0.13.5'

      - name: Print Terraform Version
        run: terraform version
