name: Test Plan Stage of CD
on:
  workflow_dispatch:

jobs:
  Planning-Stage:
    runs-on: ubuntu-latest
    env:
      versionCoreData: '10,12'

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: getRequiredTfVersion
        run: |
          if [ -n "$versionCoreData" ]; then
            IFS=',' read -ra versionCoreArray <<< "$versionCoreData"
            echo "$versionCoreArray"
            if [ "${#versionCoreArray[@]}" -gt 1 ]; then
              echo "Error in deriving terraform minimum required version. Got more than one required_version configuration from terraform deployment source : ${versionCoreArray[@]}. Please keep only one required_version configuration."
            fi
          fi
